### Register Admin
POST http://localhost:3000/auth/register
Content-Type: application/json
x-admin-secret: uma_chave_muito_forte_aqui_123

{
  "name": "Admin",
  "email": "admin@email.com",
  "password": "123456"
}

###

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "123456"
}

###

### Get Profile (rota protegida)
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}



### Get Profile (rota protegida)
GET http://localhost:3000/products/test-shopee/19899261419
Authorization: Bearer GET http://localhost:3000/products/test-shopee/19899261419
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYWFjZGE1ZS0yOWFjLTRhMjAtODAzYi1mMmRhZDk0Y2Q4NWYiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MjU2Nzg1OSwiZXhwIjoxNzcyNjU0MjU5fQ.dww7aVxXtdBowJ51f8GgOqzgEQ7MiS_Y-sYBxk5RtdQ